# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zcu102_bd/zcu102_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_bd || ORIG_REF_NAME==zcu102_bd} -quiet] -quiet

# IP: bd/zcu102_bd/ip/zcu102_bd_zynq_ultra_ps_e_0_0/zcu102_bd_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zcu102_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/zcu102_bd/ip/zcu102_bd_axi_gpio_0_0/zcu102_bd_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_bd_axi_gpio_0_0 || ORIG_REF_NAME==zcu102_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zcu102_bd/ip/zcu102_bd_xbar_0/zcu102_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_bd_xbar_0 || ORIG_REF_NAME==zcu102_bd_xbar_0} -quiet] -quiet

# IP: bd/zcu102_bd/ip/zcu102_bd_auto_ds_0/zcu102_bd_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_bd_auto_ds_0 || ORIG_REF_NAME==zcu102_bd_auto_ds_0} -quiet] -quiet

# IP: bd/zcu102_bd/ip/zcu102_bd_auto_pc_0/zcu102_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_bd_auto_pc_0 || ORIG_REF_NAME==zcu102_bd_auto_pc_0} -quiet] -quiet

# IP: bd/zcu102_bd/ip/zcu102_bd_auto_ds_1/zcu102_bd_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_bd_auto_ds_1 || ORIG_REF_NAME==zcu102_bd_auto_ds_1} -quiet] -quiet

# IP: bd/zcu102_bd/ip/zcu102_bd_auto_pc_1/zcu102_bd_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_bd_auto_pc_1 || ORIG_REF_NAME==zcu102_bd_auto_pc_1} -quiet] -quiet

# IP: bd/zcu102_bd/ip/zcu102_bd_ps8_0_axi_periph_0/zcu102_bd_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_bd_ps8_0_axi_periph_0 || ORIG_REF_NAME==zcu102_bd_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/zcu102_bd/ip/zcu102_bd_rst_ps8_0_99M_0/zcu102_bd_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_bd_rst_ps8_0_99M_0 || ORIG_REF_NAME==zcu102_bd_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: bd/zcu102_bd/zcu102_bd_ooc.xdc
