webtalk_init -webtalk_dir /home/whitney/zcu102_demo/vitis_workspace/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-06-13 18:03:32" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211432144_1777540060_210715038_808" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "nnjnnoid9e6uurmpi20itnrusl" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "931.817 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.684 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1592063771000" -context "vitis\\\\platform/1592063771000"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1592063771000"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1592063771000"
webtalk_add_data -client vitis -key processor -value "psu_cortexa53" -context "vitis\\\\platform/1592063771000"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1592063771000"
webtalk_transmit -clientid 1280504253 -regid "211432144_1777540060_210715038_808" -xml /home/whitney/zcu102_demo/vitis_workspace/webtalk/usage_statistics_ext_vitis.xml -html /home/whitney/zcu102_demo/vitis_workspace/webtalk/usage_statistics_ext_vitis.html -wdm /home/whitney/zcu102_demo/vitis_workspace/webtalk/vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
